### ISSUE TITLE
Save benchmark function interface, validate parameters

### ISSUE THREAD

**Issue by nicholasjng** [aai-institute/nnbench#3]
Currently we are overwriting the parameters for the benchmark passed in `BenchmarkRunner.run()` with the `params` slot saved on the benchmark. This is not thought through entirely, and needs changing.

Points to consider:

- [x] Remove`params` on the Benchmark class as a separate slot. All default values can be given either as variable defaults in the benchmark signature, or via `params` in `BenchmarkRunner.run()`. (#15)
- [x] We need to warn (logging) on param<->default value collision to prevent confusion. (#19)
- [x] We should think of validating the interface typing against the passed parameters, and warn/error on mismatches.  (#12)
- [x] In this sense, we can also warn if the benchmark function interface is partially/entirely untyped. (Debug log prints in `_check` if a member of any benchmark interface is untyped, i.e. `param.annotation == inspect.Parameter.empty`.) (#18)
- [x] Save benchmark function interface as a member of the `Benchmark` class. This should be a nnbench class called `Interface` etc., which is immutable/frozen, and provides easy access to function interface properties such as varnames (->`inspect.signature.parameters.keys()`), vartypes (->`inspect.signature.parameters.values()`), tuples of the two previous (->`inspect.signature.parameters.items()`), and default values (->`p.default for p in inspect.signature.parameters`). (#20)
